{
 "title": "Telco Edge monitoring",
 "time": { "from": "2020-02-10T19:32:04.010Z", "to": "2020-02-10T19:32:44.513Z" },
 "panels": [
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "SMPP Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SMPP CPU Usage Value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod_name=~\"telco-smpp-client.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SMPP Client Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod_name=~\"telco-smpp-client.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SMPP Client CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"telco-smpp-client.*\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Telco components network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name=~\"telco.*\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{pod_name}}"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{pod_name=~\"telco.*\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{pod_name}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (image_id) (kube_pod_container_info)",
     "legendFormat": "{{image_id}}"
    }
   ]
  },
  {
   "title": "Successful Request Count - telco-smpp-client (Sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time ( {app=\"telco-smpp-client\"}  |= \"DRID\" [1s])"
    }
   ]
  },
  {
   "title": "Failed Request Count - telco-smpp-client (Sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time ( {app=\"telco-smpp-client\"}  |= \"DRFID\" [1s])"
    }
   ]
  },
  {
   "title": "Bind Failure Count - telco-smpp-client (Sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time ( {app=\"telco-smpp-client\"}  |= \"BFID\" [1m])"
    }
   ]
  }
 ]
}